# Generated by Django 3.2.6 on 2022-02-27 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvalsign_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WORKFLOW_NAME', models.CharField(max_length=50)),
                ('DOC_NO', models.CharField(max_length=25)),
                ('STEP_NO', models.IntegerField()),
                ('STATION_CONDITION', models.IntegerField()),
                ('STATION_TILE', models.CharField(max_length=50)),
                ('EMP_NO', models.CharField(max_length=20)),
                ('STATUS', models.CharField(max_length=20)),
                ('HAVE_COMMENT', models.IntegerField()),
                ('APPROVAL_TIME', models.DateTimeField(default='')),
                ('ORG_APPROVER_NO', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.CharField(max_length=50)),
                ('Cost_No', models.CharField(max_length=50)),
                ('Dept_Manager', models.CharField(blank=True, max_length=50)),
                ('Manager_ID', models.CharField(blank=True, max_length=50)),
                ('Tel', models.CharField(blank=True, max_length=50)),
                ('Email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetailDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_No', models.CharField(max_length=14)),
                ('Application_Title', models.CharField(max_length=255)),
                ('Degree_urgency', models.CharField(max_length=10)),
                ('Apply_Person', models.CharField(max_length=30)),
                ('Apply_Person_Tel', models.CharField(max_length=5)),
                ('Apply_Person_Mail', models.CharField(max_length=100)),
                ('Apply_File', models.CharField(max_length=255)),
                ('Attest_File', models.CharField(max_length=255)),
                ('Mail_CC_for_applied', models.TextField()),
                ('Mail_CC_for_end', models.TextField()),
                ('Remark', models.TextField(blank=True)),
                ('Signoff_Status', models.CharField(blank=True, max_length=30)),
                ('Signoff_Station', models.CharField(blank=True, max_length=30)),
                ('Signoff_Person', models.CharField(blank=True, max_length=30)),
                ('Signoff_SupplyPerson', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Document_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WORKFLOW_NAME', models.CharField(max_length=50)),
                ('DOC_NO', models.CharField(max_length=25)),
                ('CREATE_DATE', models.DateTimeField(default='')),
                ('AUTHOR_ID', models.CharField(max_length=20)),
                ('STATION_CONDITION', models.IntegerField()),
                ('APPROVAL_TIME', models.DateTimeField(default='')),
                ('NEXT_APPROVER', models.CharField(max_length=20)),
                ('AGENT', models.CharField(max_length=30)),
                ('STATUS', models.CharField(max_length=20)),
                ('FORWARD', models.CharField(max_length=255)),
                ('REAL_APPROVAL', models.CharField(max_length=255)),
                ('SERIAL_APPROVAL', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apply_No', models.CharField(blank=True, max_length=50)),
                ('File_Name', models.CharField(blank=True, max_length=1000)),
                ('File_upload', models.FileField(blank=True, upload_to='media')),
                ('total_downloads', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Generate_Doc_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WORKFLOW_NAME', models.CharField(max_length=50)),
                ('FORMAT', models.CharField(max_length=50)),
                ('TICKET', models.CharField(max_length=24)),
                ('CREATE_DATE', models.DateTimeField(default='')),
                ('NO', models.IntegerField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='ListAppTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_Create', models.CharField(max_length=10)),
                ('app_title', models.CharField(max_length=150)),
                ('Dept', models.CharField(max_length=10)),
                ('detail', models.TextField()),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('課級主管審核', models.CharField(choices=[('yes', 'Y'), ('no', 'N')], default='no', max_length=5)),
                ('部級主管審核', models.CharField(choices=[('yes', 'Y'), ('no', 'N')], default='no', max_length=5)),
                ('處級主管審核', models.CharField(choices=[('yes', 'Y'), ('no', 'N')], default='no', max_length=5)),
                ('Bu_Header', models.CharField(choices=[('yes', 'Y'), ('no', 'N')], default='no', max_length=5)),
                ('經管簽核', models.CharField(choices=[('yes', 'Y'), ('no', 'N')], default='no', max_length=5)),
                ('結案單位', models.CharField(choices=[('yes', 'Y'), ('no', 'N')], default='no', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ListLeaderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leader_Type', models.CharField(max_length=50)),
                ('Create_At', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Process_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WORKFLOW_NAME', models.CharField(max_length=50)),
                ('PROCESS_NUMBER', models.CharField(max_length=10)),
                ('PROCESS_TITLE', models.CharField(max_length=100)),
                ('STATION_TILE', models.CharField(max_length=255)),
                ('STATION_CONDITION', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SESION_ID', models.CharField(max_length=50)),
                ('CONNECT_IP', models.CharField(max_length=50)),
                ('CONNECT_HOSTNAME', models.CharField(max_length=50)),
                ('WORK', models.CharField(max_length=255)),
                ('LAST_VISIT', models.DateTimeField(default='')),
                ('STATION_CONDITION', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Upload_File_Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apply_No', models.CharField(blank=True, max_length=50)),
                ('File_Name', models.CharField(blank=True, max_length=1000)),
                ('File_upload', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ListApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=20)),
                ('User_Name', models.CharField(max_length=30)),
                ('Setup_Person', models.CharField(max_length=30)),
                ('Setup_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Leader_Type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.listleadertype')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_grouper', models.CharField(max_length=50)),
                ('Sign_off_Type', models.CharField(max_length=50)),
                ('Sign_off_Person', models.CharField(max_length=30)),
                ('Sign_off_Status', models.CharField(max_length=30)),
                ('Sign_off_Memo', models.TextField()),
                ('Sign_off_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Application_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.detaildoc')),
            ],
        ),
        migrations.CreateModel(
            name='File_Signer_Work_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oder_No', models.FloatField()),
                ('Signer_Type', models.CharField(max_length=50)),
                ('Sign_Type', models.CharField(max_length=50)),
                ('Is_Check', models.CharField(max_length=50)),
                ('Signer', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Sign_Detail', models.CharField(max_length=50)),
                ('Sign_IP', models.CharField(max_length=50)),
                ('Sign_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Sign_FileNameOld', models.CharField(max_length=100)),
                ('Sign_FileNameNew', models.CharField(max_length=100)),
                ('Sign_Agent', models.CharField(max_length=30)),
                ('Application_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.detaildoc')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree_of_urgency', models.CharField(max_length=10)),
                ('Application_Title', models.CharField(max_length=255)),
                ('Apply_File', models.CharField(max_length=255)),
                ('Attest_File', models.CharField(max_length=255)),
                ('Apply_Person', models.CharField(max_length=30)),
                ('Signoff_Status', models.CharField(max_length=30)),
                ('Signoff_Station', models.CharField(max_length=30)),
                ('Signoff_Person', models.CharField(max_length=30)),
                ('Signoff_SupplyPerson', models.CharField(max_length=30)),
                ('Application_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.detaildoc')),
            ],
        ),
    ]
